### PR TITLE
Upgrade kubernetes-model to 3.0.3

### LINKED ISSUE #9: Upgrade to kubernetes-model 3.0.2
New version of kubernetes-model  is out. Also new version of kotlin. 

PR incomming.

### PR DESCRIPTION
**Pull request by bjartek**
I ran the generation goal but there was no changes, so not sure if we even need a release here? Or is there something that has change?

Fixes #9

### CODE REVIEW

**Comment by fkorotkov** [comment]
@bjartek thanks for the PR. Please regenerate stubs by running `./gradlew :kubernetes:generator:run`

**Comment by bjartek** [comment]
I have tried doing that twice not but it does not update anything.

**Comment by fkorotkov** [comment]
Seems they haven't changed much.

**Comment by fkorotkov** [comment]
Published 1.2.1

**Comment by bjartek** [comment]
Thanks!

**Pull request merged**
